
CREATE DATABASE CCCD;
GO
USE CCCD;
GO
CREATE TABLE CCCD(
ID INT PRIMARY KEY IDENTITY NOT NULL,
[DATA] NVARCHAR(MAX) NULL,
CREATED_DATE DATETIME NULL
)
GO
ALTER DATABASE CCCD SET ENABLE_BROKER WITH ROLLBACK IMMEDIATE;