//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadCard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCCD
    {
        public int ID { get; set; }
        public string DATA { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
    }
}
